#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
  name: argocd-dex-server
  namespace: gemcloud-workflow-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
        app.kubernetes.io/part-of: argocd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-dex-server
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - command:
        - /shared/argocd-util
        - rundex
        image: "{{ global.repository | default('docker.io/kubegems')}}/dex:v2.27.0"
        imagePullPolicy: IfNotPresent
        name: dex
        ports:
        - containerPort: 5556
        - containerPort: 5557
        - containerPort: 5558
        volumeMounts:
        - mountPath: /shared
          name: static-files
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd-util
        - /shared
        image: "{{ global.repository | default('docker.io/kubegems') }}/argocd:{{ core_plugins.argocd.details.version | default('latest')}}"
        imagePullPolicy: IfNotPresent 
        name: copyutil
        volumeMounts:
        - mountPath: /shared
          name: static-files
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
        - name: {{  global.imagepullsecret | default('kubgems') }}
      {% endif %}
      serviceAccountName: argocd-dex-server
      volumes:
      - emptyDir: {}
        name: static-files