apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gems-docs
  name: gems-docs
  namespace: gemcloud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gems-docs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gems-docs
    spec:
      containers:
      - image: "docker.io/kubegems/gems-docs:{{ core_plugins.gems_worker.details.version }}"
        imagePullPolicy: IfNotPresent
        name: gems-docs
        ports:
        - containerPort: 8080
          name: http-8080
        resources:
          limits:
            cpu: 200m 
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: gemcloud
      restartPolicy: Always