- name: Core Plugins | Eventer 
  kubernetes.core.k8s:
    state: '{{ "present" if core_plugins.eventer.enabled else "absent" }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - eventer/sa.yaml
    - eventer/clusterrole.yaml
    - eventer/clusterrolebinding.yaml
    - eventer/configmap.yaml
    - eventer/deploy.yaml