- name: Core Plugins | Logging Operator | CRDs
  when: core_plugins.logging.enabled
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - logging-operator/operator/crds/logging.yaml
    - logging-operator/operator/crds/clusterflows.yaml
    - logging-operator/operator/crds/flows.yaml
    - logging-operator/operator/crds/outputs.yaml
    - logging-operator/operator/crds/clusteroutputs.yaml 

- name: Core Plugins | Logging Operator Service
  community.kubernetes.k8s:
    state: '{{ "present" if core_plugins.logging.enabled else "absent" }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - logging-operator/operator/sa.yaml
    - logging-operator/operator/clusterrole.yaml
    - logging-operator/operator/clusterrolebinding.yaml
    - logging-operator/operator/deploy.yaml
    - logging-operator/operator/service.yaml

- name: Core Plugins | Logging Operator Collector
  community.kubernetes.k8s:
    state: '{{ "present" if core_plugins.logging.enabled else "absent" }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  ignore_errors: true
  with_items:
    - logging-operator/logging.yaml
    - logging-operator/flows.yaml
    - logging-operator/clusteroutputs.yaml

- name: Core Plugins | Loki Recording Rules Configuration
  community.kubernetes.k8s:
    state: '{{ "present" if core_plugins.logging.enabled and core_plugins.logging.operator.loki.enabled else "absent" }}'
    definition: "{{ lookup('file', item) | from_yaml }}"
  with_items:
    - loki-stack/recording_rules.yaml

- name: Core Plugins | Loki Stack
  community.kubernetes.k8s:
    state: '{{ "present" if core_plugins.logging.enabled and core_plugins.logging.operator.loki.enabled else "absent" }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - loki-stack/redis/statefulset.yaml
    - loki-stack/redis/svc.yaml
    - loki-stack/redis/configmap.yaml
    - loki-stack/loki/configmap.yaml
    - loki-stack/loki/statefulset.yaml
    - loki-stack/loki/svc.yaml