{
 "title": "loki-redis",
 "description": "GemCloud Logging System Cache",
 "tags": [
  "loki",
  "cache",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Redis版本",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "AOF",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_enabled{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "最近慢查询id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slowlog_last_id{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "永久key比例",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 1 - sum(redis_db_keys_expiring{job=\"loki-redis-metrics\"})  / sum(redis_db_keys{job=\"loki-redis-metrics\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "Slave状态",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "Slave节点",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Slave延迟状态",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds{job=\"loki-redis-metrics\"}"
    }
   ]
  },
  {
   "title": "Items数量 by db",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"loki-redis-metrics\"}) by (db)",
     "legendFormat": "{{ db }} "
    },
    {
     "expr": "redis_config_maxclients{job=\"loki-redis-metrics\"}",
     "legendFormat": "max client"
    }
   ]
  },
  {
   "title": "各操作top5的qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, rate(redis_commands_total{job=\"loki-redis-metrics\"}[5m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "各操作top5的qps耗时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " topk(5,rate(redis_commands_duration_seconds_total{job=\"loki-redis-metrics\"}[5m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{job=\"loki-redis-metrics\"}[5m]) + rate(redis_cpu_sys_seconds_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"loki-redis-metrics\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "入口"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "出口"
    }
   ]
  },
  {
   "title": "最慢查询时间",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_last_slow_execution_duration_seconds{job=\"loki-redis-metrics\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "最近fork线程时间",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_latest_fork_seconds{job=\"loki-redis-metrics\"}",
     "legendFormat": "forktime"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=\"loki-redis-metrics\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Slave数据偏差",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_slave_offset_bytes{job=\"loki-redis-metrics\"}",
     "legendFormat": "{{slave_ip}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=\"loki-redis-metrics\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=\"loki-redis-metrics\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "connected",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"loki-redis-metrics\"}",
     "legendFormat": "connected"
    }
   ]
  }
 ]
}