- name: Kubernetes Plugins | Flannel
  when: kubernetes_plugins.flannel is defined
  kubernetes.core.k8s:
    #state: '{{"present" if kubernetes_plugins.flannel.enabled else ( "absent" if kubernetes_plugins.flannel.force_delete else "present" )}}'
    state: '{{ "present" if kubernetes_plugins.flannel.enabled else "absent" }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - flannel/sa.yaml
    - flannel/psp.yaml
    - flannel/clusterrole.yaml
    - flannel/clusterrolebinding.yaml
    - flannel/configmap.yaml
    - flannel/daemonset.yaml